name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Say Hello World!
        run: echo 'Hello World!'
